spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edu?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: localhost
    database: 0
    password: 123456

qiniu:
  accessKey: -Mi-hewJgdcYP-8oYT5_SvTdyTXAvy9QFEagb5X_
  secretKey: TEYiU6UXu3LdVpCLYR98k2HQxBDx0yUKuJ7TAo9e
  bucket: teabuketname
  prefix: qk4uqldqz.hn-bkt.clouddn.com

